In [26]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('studentperformance.csv')
df.head()

sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  traveltime  \
0   F   13       U     GT3       A     4     4  at_home   teacher           2   
1   F   12       U     GT3       T     1     1  at_home     other           1   
2   F   10       U     LE3       T     1     1  at_home     other           1   
3   F   10       U     GT3       T     4     2   health  services           1   
4   F   11       U     GT3       T     3     3    other     other           1   

   ...  paid  activities nursery higher internet famrel freetime health  \
0  ...    no          no     yes    yes       no      4        3      3   
1  ...    no          no      no    yes      yes      5        3      3   
2  ...    no          no     yes    yes      yes      4        3      3   
3  ...    no         yes     yes    yes      yes      3        2      5   
4  ...    no          no     yes    yes       no      4        3      5   

  absences  score  
0        4     68  
1        2     59  
2        6     60  
3        0     70  
4        0     92  

[5 rows x 24 columns]

In [27]:
df.replace({'#':50},inplace =True)
df['score'] = pd.to_numeric(df['score'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 649 entries, 0 to 648
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   sex         649 non-null    object
 1   age         649 non-null    int64 
 2   address     649 non-null    object
 3   famsize     649 non-null    object
 4   Pstatus     649 non-null    object
 5   Medu        649 non-null    int64 
 6   Fedu        649 non-null    int64 
 7   Mjob        649 non-null    object
 8   Fjob        649 non-null    object
 9   traveltime  649 non-null    int64 
 10  studytime   649 non-null    int64 
 11  failures    649 non-null    int64 
 12  schoolsup   649 non-null    object
 13  famsup      649 non-null    object
 14  paid        649 non-null    object
 15  activities  649 non-null    object
 16  nursery     649 non-null    object
 17  higher      649 non-null    object
 18  internet    649 non-null    object
 19  famrel      649 non-null    int64 
 20  freetime  

In [28]:
df.columns

Index(['sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob',
       'Fjob', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup',
       'paid', 'activities', 'nursery', 'higher', 'internet', 'famrel',
       'freetime', 'health', 'absences', 'score'],
      dtype='object')

df = df[['sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup','paid', 'activities', 'nursery', 'higher', 'internet', 'famrel','freetime', 'health', 'absences', 'score']]

In [29]:
cat = df[['sex','address', 'famsize', 'Pstatus','schoolsup', 'famsup', 'paid',
       'activities', 'nursery', 'higher', 'internet']]
for col in cat:
    print(df[col].unique())

['F' 'M']
['U' 'R']
['GT3' 'LE3']
['A' 'T']
['yes' 'no']
['no' 'yes']
['no' 'yes']
['no' 'yes']
['yes' 'no']
['yes' 'no']
['no' 'yes']


In [30]:
num = [ 'age',  'Medu', 'Fedu', 'traveltime', 'studytime', 'failures',   'famrel','freetime', 'health', 'absences', 'score']
for col in num:
    print(df[col].unique())

[13 12 10 11 14 17 15 16]
[4 1 3 2 0]
[4 1 2 3 0]
[2 1 3 4]
[2 3 1 4]
[0 3 1 2]
[4 5 3 1 2]
[3 2 4 1 5]
[3 5 1 2 4]
[ 4  2  6  0 10  8 16 14  1 12 24 22 32 30 21 15  9 18 26  7 11  5 13  3]
[68 59 60 70 92 73 75 71 79 80 56 98 77 55 66 62 69 78 85 82 90 86 67 84
 72 50 76 54 45 52 57 63 89 65 61 51 87 53 64 49 83 58 88 95 81 93 91 48
 74]


In [31]:
from sklearn.preprocessing import LabelEncoder
sex_r = LabelEncoder()
df['sex'] = sex_r.fit_transform(df['sex'])
df["sex"].unique()

array([0, 1])

In [32]:
address_r = LabelEncoder()
df['address'] = address_r.fit_transform(df['address'])
df["address"].unique()

array([1, 0])

In [33]:
famsize_r = LabelEncoder()
df['famsize'] = famsize_r.fit_transform(df['famsize'])
df["famsize"].unique()

array([0, 1])

In [34]:
Pstatus_r = LabelEncoder()
df['Pstatus'] = Pstatus_r.fit_transform(df['Pstatus'])
df["Pstatus"].unique()

array([0, 1])

In [35]:
schoolsup_r = LabelEncoder()
df['schoolsup'] = schoolsup_r.fit_transform(df['schoolsup'])
df["schoolsup"].unique()

array([1, 0])

In [36]:
paid_r = LabelEncoder()
df['paid'] = paid_r.fit_transform(df['paid'])
df["paid"].unique()

array([0, 1])

In [37]:
activities_r = LabelEncoder()
df['activities'] = activities_r.fit_transform(df['activities'])
df["activities"].unique()

array([0, 1])

In [38]:
nursery_r = LabelEncoder()
df['nursery'] = nursery_r.fit_transform(df['nursery'])
df["nursery"].unique()

array([1, 0])

In [39]:
higher_r = LabelEncoder()
df['higher'] = higher_r.fit_transform(df['higher'])
df["higher"].unique()

array([1, 0])

In [40]:
internet_r = LabelEncoder()
df['internet'] = internet_r.fit_transform(df['internet'])
df["internet"].unique()

array([0, 1])

In [41]:

famsup_r = LabelEncoder()
df['famsup'] = famsup_r.fit_transform(df['famsup'])
df["famsup"].unique()

array([0, 1])

In [42]:
df.drop(['Mjob', 'Fjob'], axis=1, inplace=True)

In [43]:
X = df.drop("score", axis=1)
y = df["score"]

In [44]:
from sklearn.svm import SVR
model = SVR(kernel='rbf', degree=3, C=1.0, gamma='auto')
model.fit(X,y.values)

SVR(gamma='auto')

In [45]:
from sklearn.metrics import mean_squared_error, mean_absolute_error,mean_absolute_percentage_error,r2_score
import numpy as np
y_pred = model.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
erro2 = mean_absolute_percentage_error(y,y_pred)
acuuracy = r2_score(y,y_pred)
print(acuuracy)
print(error)
print(erro2)

0.06786342662505707
10.172827956051853
0.119538515998449


In [46]:
error = np.sqrt(mean_squared_error(y, y_pred))
print("{:,.02f}".format(error))

10.17


In [47]:
cat

sex address famsize Pstatus schoolsup famsup paid activities nursery  \
0     F       U     GT3       A       yes     no   no         no     yes   
1     F       U     GT3       T        no    yes   no         no      no   
2     F       U     LE3       T       yes     no   no         no     yes   
3     F       U     GT3       T        no    yes   no        yes     yes   
4     F       U     GT3       T        no    yes   no         no     yes   
..   ..     ...     ...     ...       ...    ...  ...        ...     ...   
644   F       R     GT3       T        no     no   no        yes      no   
645   F       U     LE3       T        no    yes   no         no     yes   
646   F       U     GT3       T        no     no   no        yes     yes   
647   M       U     LE3       T        no     no   no         no      no   
648   M       R     LE3       T        no     no   no         no      no   

    higher internet  
0      yes       no  
1      yes      yes  
2      yes      yes  
3      yes      yes  
4      yes       no  
..     ...      ...  
644    yes      yes  
645    yes      yes  
646    yes       no  
647    yes      yes  
648    yes      yes  

[649 rows x 11 columns]

In [48]:
import pickle
data = {'model':model,"sex": sex_r, "address": address_r, "famsize": famsize_r,"pstatus": Pstatus_r,"schoolsup": schoolsup_r, "famsup": famsup_r, "paid": paid_r,"activities": activities_r, "nursey": nursery_r, "higher": higher_r,"internet": internet_r}
with open('reg001.pkl', 'wb') as file:
    pickle.dump(data, file)

In [49]:
with open('reg001.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]

In [50]:
X=np.array([['F'	,12	,'U',	'GT3',	'A',	4,	4,		2,	2,	0,	'yes',	'yes',	'no',	'no',	'yes',	'yes',	'no',	4,	1,	1,	2]])

In [51]:
X[:, 0] = sex_r.transform(X[:,0])
X[:, 2] = address_r.transform(X[:,2])
X[:, 3] = famsize_r.transform(X[:,3])
X[:, 4] = Pstatus_r.transform(X[:,4])
X[:, 10] = schoolsup_r.transform(X[:,10])
X[:, 11] = famsup_r.transform(X[:,11])
X[:, 12] = paid_r.transform(X[:,12])
X[:, 13] = activities_r.transform(X[:,13])
X[:, 14] = nursery_r.transform(X[:,14])
X[:, 15] = higher_r.transform(X[:,15])
X[:, 16] = internet_r.transform(X[:,16])
X = X.astype(float)
X


array([[ 0., 12.,  1.,  0.,  0.,  4.,  4.,  2.,  2.,  0.,  1.,  1.,  0.,
         0.,  1.,  1.,  0.,  4.,  1.,  1.,  2.]])

In [52]:
y_pred = model.predict(X)
y_pred

c:\Users\User\Anaconda3\Earlycode\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([68.73506843])

In [53]:
import pickle
data = {'model':model,"sex": sex_r, "address": address_r, "famsize": famsize_r,"pstatus": Pstatus_r,"schoolsup": schoolsup_r, "famsup": famsup_r, "paid": paid_r,"activities": activities_r, "nursey": nursery_r, "higher": higher_r,"internet": internet_r}
with open('reg002.pkl', 'wb') as file:
    pickle.dump(data, file)

In [54]:
with open('reg002.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]

In [55]:
y_pred = regressor_loaded.predict(X)
y_pred

c:\Users\User\Anaconda3\Earlycode\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([68.73506843])

In [56]:
df.columns

Index(['sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid',
       'activities', 'nursery', 'higher', 'internet', 'famrel', 'freetime',
       'health', 'absences', 'score'],
      dtype='object')

In [57]:
data

{'model': SVR(gamma='auto'),
 'sex': LabelEncoder(),
 'address': LabelEncoder(),
 'famsize': LabelEncoder(),
 'pstatus': LabelEncoder(),
 'schoolsup': LabelEncoder(),
 'famsup': LabelEncoder(),
 'paid': LabelEncoder(),
 'activities': LabelEncoder(),
 'nursey': LabelEncoder(),
 'higher': LabelEncoder(),
 'internet': LabelEncoder()}